#!/bin/bash 

# Colours for progress and error reporting
ERROR="\033[1;31m"
GOOD="\033[1;32m"
WARN="\033[1;35m"
INFO="\033[1;34m"
BOLD="\033[1m"

cecho() {
  # Display messages in a specified colour
  COL=$1; shift
  echo -e "${COL}$@\033[0m"
}

# Verify that one_line_install is called from dcs2 root
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
if [ "$(pwd)/scripts" != "${SCRIPT_DIR}" ]; then
  cecho ${ERROR} "ERROR: one_line_install has to be called from the dcs2 root directory."
  exit 1
fi

python scripts/tui.py

bash dcs2_autogenerated-build-command.sh
