# This module finds ScaLAPACK

unset(SCALAPACK_LIBRARY)
unset(SCALAPACK_INCLUDE_DIR)

find_path(SCALAPACK_INCLUDE_DIR NAMES scalapack.h HINTS ${SCALAPACK_DIR} ${CMAKE_INSTALL_PREFIX}/scalapack/${SCALAPACK_VERSION})
find_library(SCALAPACK_LIBRARY NAMES scalapack HINTS ${SCALAPACK_DIR} ${CMAKE_INSTALL_PREFIX}/scalapack/${SCALAPACK_VERSION})

if(SCALAPACK_INCLUDE_DIR AND SCALAPACK_LIBRARY)
  # Derive SCALAPACK_DIR from ScaLAPACK_LIBRARY
  get_filename_component(SCALAPACK_DIR "${SCALAPACK_LIBRARY}" DIRECTORY)

  set(SCALAPACK_FOUND TRUE)
else()
  set(SCALAPACK_FOUND FALSE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SCALAPACK DEFAULT_MSG SCALAPACK_LIBRARY SCALAPACK_INCLUDE_DIR)

mark_as_advanced(SCALAPACK_INCLUDE_DIR SCALAPACK_LIBRARY)
