# This module finds MUMPS

unset(MUMPS_INCLUDE_DIR)
unset(MUMPS_LIBRARY)

find_path(MUMPS_INCLUDE_DIR NAMES mumps.h HINTS ${MUMPS_DIR} ${CMAKE_INSTALL_PREFIX}/mumps/${MUMPS_VERSION})
find_library(MUMPS_LIBRARY NAMES mumps HINTS ${MUMPS_DIR} ${CMAKE_INSTALL_PREFIX}/mumps/${MUMPS_VERSION})

if(MUMPS_INCLUDE_DIR AND MUMPS_LIBRARY)
  # Derive MUMPS_DIR from ScaLAPACK_LIBRARY
  get_filename_component(MUMPS_DIR "${MUMPS_LIBRARY}" DIRECTORY)

  set(MUMPS_FOUND TRUE)
else()
  set(MUMPS_FOUND FALSE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MUMPS DEFAULT_MSG MUMPS_LIBRARY MUMPS_INCLUDE_DIR)

mark_as_advanced(MUMPS_INCLUDE_DIR MUMPS_LIBRARY)
