name: Auto Package Update

on:
  schedule:
    - cron: "0 4 * * 0"  # Runs every Sunday at 04:00 UTC
  workflow_dispatch:     # Allow manual triggering via GitHub UI

jobs:
  update-deps:
    name: Update packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install requests packaging

      - name: Run Update Script
        run: python scripts/update_packages.py --all | tee update-log.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-update"
          title: "Weekly Package Update"
          branch: auto-update
          body-path: update-log.txt
          labels: |
            automated

