name: Platform Test Ubuntu-25.04

on:
  workflow_dispatch:

jobs:
  fedora-test:
    name: Ubuntu-25.04
    runs-on: [self-hosted, ubuntu-25.04]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./dcs2.sh -U OFF -A ON -j 12 --blas-stack default --cmake-flags "-D TPL_ENABLE_GMSH=ON"
